apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo-production
  labels:
    app: odoo
    tier: application
spec:
  type: ClusterIP
  ports:
  - port: 8069
    targetPort: 8069
    protocol: TCP
    name: http
  - port: 8072
    targetPort: 8072
    protocol: TCP
    name: longpolling
  selector:
    app: odoo
    tier: application
