apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: odoo-production
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo123  # Change in production!
